-- Google Cloud Storage Setup for User Uploads
-- This is a guide for setting up GCS bucket equivalent to Supabase storage

-- Prerequisites:
-- 1. GCP Project with Cloud Storage API enabled
-- 2. Service Account with Storage Admin or Object Admin role
-- 3. For Vercel: Workload Identity Federation configured
-- 4. Environment variables set in Vercel or .env:
--    GCP_PROJECT_ID, GCP_BUCKET_NAME, GCP_PROJECT_NUMBER,
--    GCP_SERVICE_ACCOUNT_EMAIL, GCP_WORKLOAD_IDENTITY_POOL_ID,
--    GCP_WORKLOAD_IDENTITY_PROVIDER_ID
--    For local: GOOGLE_APPLICATION_CREDENTIALS=path/to/key.json

-- Step 1: Create the bucket
-- Run: npx tsx api/create-bucket-gcs.ts
-- Or manually in GCP Console: Storage > Buckets > Create bucket
-- Bucket name: user-uploads (or as per GCP_BUCKET_NAME)
-- Location: Choose appropriate region
-- Storage class: Standard
-- Access control: Uniform (recommended for fine-grained control)

-- Step 2: Configure CORS (if using bucket.create in script, it's done)
-- In GCP Console: Bucket > Configuration > CORS configuration
-- Add:
[
  {
    "origin": [
      "http://localhost:5173",
      "http://localhost:5174",
      "http://localhost:3000",
      "https://epimetheusproject.vercel.app",
      "https://epimetheus.ai",
      "https://www.epimetheus.ai"
    ],
    "method": ["GET", "POST", "PUT", "DELETE"],
    "responseHeader": ["Content-Type"],
    "maxAgeSeconds": 3600
  }
]

-- Step 3: KEEP THE BUCKET PRIVATE — do NOT grant public read
-- The previous instruction here ("Make bucket public for read access" /
-- "Grant Storage Object Viewer to allUsers") is precisely what made every
-- profile photo world-readable at a guessable path (users/<userId>/profile.<ext>)
-- permanently — including after account deletion. Public read is now removed:
--   • reads go through createSignedUrl() with a 1h TTL
--   • Supabase equivalent: storage.buckets.public = false, applied by
--     supabase/migrations/20240101001000_storage_private_bucket.sql
-- Leave the bucket private; grant the service account Object Admin only.

-- Step 4: IAM Policies for uploads
-- The service account needs Storage Object Admin on the bucket
-- In GCP Console: Bucket > Permissions > Add
-- Add the service account email with Storage Object Admin role

-- Step 5: For user-specific uploads
-- Use signed URLs generated by api/upload.ts
-- Frontend requests upload URL with userId, then uploads directly to GCS
-- Files are stored in userId/filename structure for isolation

-- Note: Unlike Supabase RLS, GCS uses signed URLs for secure uploads
-- No direct equivalent to RLS, but signed URLs provide similar security

-- Object policies — owner-scoped only.
-- CORRECTED: the previous revision of this file matched
-- `(storage.foldername(name))[1] = auth.uid()::text`, but folders are laid out
-- `users/<uid>/...`, so element [1] is the literal 'users' and the uid is
-- element [2]. Those policies therefore matched nothing while still looking
-- correct in review. The canonical, migration-managed set lives in
-- supabase/migrations/20240101001000_storage_private_bucket.sql; this file is a
-- legacy GCS guide and is kept in sync for operators who paste it by hand.
DROP POLICY IF EXISTS "Public can view files" ON storage.objects;
DROP POLICY IF EXISTS "Users can view their own files" ON storage.objects;
CREATE POLICY "Users can view their own files" ON storage.objects
FOR SELECT USING (
  bucket_id = 'user-uploads'
  AND auth.role() = 'authenticated'
  AND (storage.foldername(name))[1] = 'users'
  AND (storage.foldername(name))[2] = auth.uid()::text
);

DROP POLICY IF EXISTS "Users can delete their own files" ON storage.objects;
CREATE POLICY "Users can delete their own files" ON storage.objects
FOR DELETE USING (
  bucket_id = 'user-uploads'
  AND auth.role() = 'authenticated'
  AND (storage.foldername(name))[1] = 'users'
  AND (storage.foldername(name))[2] = auth.uid()::text
);

DROP POLICY IF EXISTS "Users can update their own files" ON storage.objects;
CREATE POLICY "Users can update their own files" ON storage.objects
FOR UPDATE USING (
  bucket_id = 'user-uploads'
  AND auth.role() = 'authenticated'
  AND (storage.foldername(name))[1] = 'users'
  AND (storage.foldername(name))[2] = auth.uid()::text
);
