import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import Logo from '../components/Logo';

/**
 * Privacy Policy — public route, no auth required.
 *
 * IMPORTANT: This is a plain-English template that describes how the Epimetheus
 * codebase actually handles data today (Supabase Auth + Postgres + Storage,
 * Regolo AI for LLM calls, optional Sentry, server-derived userId, RLS, etc.).
 * It is not legal advice. Replace placeholders and have a lawyer review for
 * your jurisdiction (GDPR, CCPA, Philippines DPA 10173, etc.) before shipping
 * to production.
 */
export default function PrivacyPage() {
  const EFFECTIVE_DATE = 'May 25, 2026';

  return (
    <div className="min-h-screen bg-mystic-950 text-slate-200">
      <header className="border-b border-white/5 bg-mystic-950/80 backdrop-blur sticky top-0 z-10">
        <div className="max-w-3xl mx-auto px-4 py-4 flex items-center justify-between">
          <Link
            to="/login"
            className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-slate-100 transition-colors"
          >
            <ArrowLeft className="w-4 h-4" aria-hidden="true" />
            Back
          </Link>
          <Logo size="md" />
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-12 space-y-8">
        <div className="space-y-2">
          <p className="font-mono text-[11px] tracking-[0.3em] uppercase text-accent-primary">
            Legal
          </p>
          <h1 className="text-4xl font-semibold tracking-tight text-slate-50">
            Privacy Policy
          </h1>
          <p className="text-sm text-slate-500">Effective: {EFFECTIVE_DATE}</p>
        </div>

        <p className="text-sm text-slate-400 leading-relaxed">
          This Privacy Policy explains what information we collect, how we use
          it, and your choices. It applies to your use of Epimetheus
          (&quot;Service&quot;).
        </p>

        <Section title="1. Information We Collect">
          <p>We collect three categories of information:</p>

          <h3 className="text-slate-200 font-medium mt-4">
            (a) Information you provide
          </h3>
          <ul className="list-disc list-inside space-y-2">
            <li>
              <strong className="text-slate-200">Account info:</strong> email
              address, password (hashed by our authentication provider),
              display name, optional profile photo, optional bio and contact
              handles.
            </li>
            <li>
              <strong className="text-slate-200">Assessment answers</strong>{' '}
              and short personality questionnaires you complete.
            </li>
            <li>
              <strong className="text-slate-200">
                Scenario inputs and dossier notes
              </strong>{' '}
              you write describing situations or people you want to analyze.
            </li>
            <li>
              <strong className="text-slate-200">Advisor chat messages</strong>
              {' '}you send to the AI advisor.
            </li>
            <li>
              <strong className="text-slate-200">
                Field reports, comments, and feedback
              </strong>{' '}
              you submit.
            </li>
          </ul>

          <h3 className="text-slate-200 font-medium mt-4">
            (b) Information generated by the Service
          </h3>
          <ul className="list-disc list-inside space-y-2">
            <li>
              <strong className="text-slate-200">AI outputs:</strong> typed
              archetype results, trait analyses, behavioral indicators, task
              lists, and chat responses produced by our AI provider in response
              to your inputs.
            </li>
            <li>
              <strong className="text-slate-200">Calibration history</strong>
              {' '}and usage data linking your account to your past analyses.
            </li>
          </ul>

          <h3 className="text-slate-200 font-medium mt-4">
            (c) Information collected automatically
          </h3>
          <ul className="list-disc list-inside space-y-2">
            <li>
              <strong className="text-slate-200">Technical info:</strong>{' '}
              IP address (used for rate limiting and abuse prevention), browser
              user agent, approximate timestamps of requests.
            </li>
            <li>
              <strong className="text-slate-200">Error reports:</strong> if
              Sentry error monitoring is enabled, anonymized error stack traces
              and the user ID associated with the error.
            </li>
          </ul>
        </Section>

        <Section title="2. How We Use Information">
          <ul className="list-disc list-inside space-y-2">
            <li>To create and operate your account.</li>
            <li>To generate AI analyses and chat responses you request.</li>
            <li>To save your calibrations, dossiers, and chat history.</li>
            <li>
              To rate-limit requests and detect abuse (using your IP address
              and a short-lived counter).
            </li>
            <li>To send you transactional emails (account verification, password reset).</li>
            <li>To improve reliability by triaging error reports.</li>
            <li>To enforce our Terms of Service and comply with applicable law.</li>
          </ul>
        </Section>

        <Section title="3. Legal Bases (for users in the EEA / UK)">
          <p>
            Where applicable, we process personal data based on:
          </p>
          <ul className="list-disc list-inside space-y-2 mt-2">
            <li>
              <strong className="text-slate-200">Contract:</strong> to provide
              the Service you signed up for.
            </li>
            <li>
              <strong className="text-slate-200">Legitimate interests:</strong>{' '}
              to maintain Service security, detect abuse, and improve reliability.
            </li>
            <li>
              <strong className="text-slate-200">Consent:</strong> for optional
              analytics or marketing communications, where applicable.
            </li>
            <li>
              <strong className="text-slate-200">Legal obligation:</strong>{' '}
              when required by law.
            </li>
          </ul>
        </Section>

        <Section title="4. AI Processing">
          <p>
            When you submit a scenario, message, or other input that requires
            AI analysis, we send the relevant portions of your input to our AI
            provider, Regolo AI. Regolo processes the input to generate a
            response that we return to you and store in your account history.
          </p>
          <p className="mt-3">
            We do not currently use your inputs or AI outputs to train external
            models. Our agreement with Regolo and any future provider is
            structured so that your content is processed solely to fulfill your
            requests.
          </p>
          <p className="mt-3">
            <strong className="text-slate-200">
              Be cautious about what you share.
            </strong>{' '}
            Do not include sensitive personal data about yourself or others
            (full government IDs, financial account numbers, biometric data,
            health records) in AI prompts unless strictly necessary.
          </p>
        </Section>

        <Section title="5. Information About Other People">
          <p>
            Epimetheus lets you write notes, dossiers, and scenarios that may
            describe other people. You are responsible for ensuring you have
            the right to record this information and that you do not violate
            applicable privacy laws or the rights of others.
          </p>
          <p className="mt-3">
            We do not provide profiles of identified third parties through
            search or directory features. The notes you write are visible only
            to you (and to administrators of the Service in limited
            circumstances such as moderation or troubleshooting).
          </p>
        </Section>

        <Section title="6. Sharing">
          <p>We share information only as described below:</p>
          <ul className="list-disc list-inside space-y-2 mt-2">
            <li>
              <strong className="text-slate-200">Service providers:</strong>{' '}
              Supabase (database, auth, storage), Regolo AI (LLM inference),
              Vercel (hosting), Sentry (optional error monitoring), our email
              delivery provider for transactional emails. They process data on
              our behalf, under contractual confidentiality and security
              obligations.
            </li>
            <li>
              <strong className="text-slate-200">Community features:</strong>{' '}
              if you publish a Field Report or comment, the content you submit
              is visible to other authenticated users of the Service. Your
              display name and avatar are visible alongside your published
              content.
            </li>
            <li>
              <strong className="text-slate-200">Legal:</strong> we may
              disclose information if required by law, court order, or to
              protect the rights, property, or safety of users or the public.
            </li>
            <li>
              <strong className="text-slate-200">Business transfers:</strong>{' '}
              if we are involved in a merger, acquisition, or asset sale, your
              information may be transferred as part of that transaction; we
              will notify you of the change.
            </li>
          </ul>
          <p className="mt-3">
            <strong className="text-slate-200">
              We do not sell your personal information.
            </strong>
          </p>
        </Section>

        <Section title="7. Security">
          <p>We use technical and organizational measures designed to protect your information, including:</p>
          <ul className="list-disc list-inside space-y-2 mt-2">
            <li>
              Row-level security on every database table that stores user
              data, so other users cannot read your records.
            </li>
            <li>
              Server-side derivation of your user ID from your authenticated
              session token, so a compromised client cannot impersonate
              another user.
            </li>
            <li>
              HTTPS in transit, encryption at rest where supported by our
              providers.
            </li>
            <li>
              Magic-byte verification and size limits on uploaded images.
            </li>
            <li>Rate limiting on AI and write endpoints.</li>
            <li>
              A strict Content Security Policy and CSRF protection on all
              state-changing endpoints.
            </li>
          </ul>
          <p className="mt-3">
            No system is perfectly secure. If you believe your account has
            been compromised, contact us immediately.
          </p>
        </Section>

        <Section title="8. Data Retention">
          <p>
            We keep your account information and content for as long as your
            account is active. You can delete most content (calibrations,
            dossiers, chat sessions, field reports, favorites) from within the
            app at any time.
          </p>
          <p className="mt-3">
            When you delete your account, we delete or anonymize your
            personal data within a reasonable period, except where we are
            required to retain it for legal, regulatory, or fraud-prevention
            purposes. Backups containing residual copies are rotated out of
            existence within our normal backup cycle.
          </p>
        </Section>

        <Section title="9. Your Rights">
          <p>Depending on where you live, you may have the right to:</p>
          <ul className="list-disc list-inside space-y-2 mt-2">
            <li>Access the personal data we hold about you.</li>
            <li>Correct inaccurate data.</li>
            <li>Delete your data (right to erasure).</li>
            <li>Restrict or object to certain processing.</li>
            <li>Receive a copy of your data in a portable format.</li>
            <li>Withdraw consent where processing is based on consent.</li>
            <li>
              Lodge a complaint with your local data-protection authority.
            </li>
          </ul>
          <p className="mt-3">
            To exercise these rights, email{' '}
            <a
              href="mailto:epimetheus.support@gmail.com?subject=Data%20rights%20request%20%E2%80%94%20Epimetheus&body=Hi%20Epimetheus%20team%2C%0A%0AI%20am%20requesting%20%5Baccess%20%2F%20correction%20%2F%20deletion%20%2F%20portability%20%2F%20other%5D%20of%20my%20personal%20data.%0A%0AAccount%20email%3A%20%5Byour%20email%5D%0A%0AThanks%2C%0A"
              className="text-accent-primary hover:underline"
            >
              epimetheus.support@gmail.com
            </a>
            {' '}(or{' '}
            <a
              href="https://mail.google.com/mail/?view=cm&fs=1&to=epimetheus.support@gmail.com&su=Data%20rights%20request%20%E2%80%94%20Epimetheus&body=Hi%20Epimetheus%20team%2C%0A%0AI%20am%20requesting%20%5Baccess%20%2F%20correction%20%2F%20deletion%20%2F%20portability%20%2F%20other%5D%20of%20my%20personal%20data.%0A%0AAccount%20email%3A%20%5Byour%20email%5D%0A%0AThanks%2C%0A"
              target="_blank"
              rel="noopener noreferrer"
              className="text-accent-primary hover:underline"
            >
              open in Gmail
            </a>
            ). We may need to verify your identity before fulfilling the
            request.
          </p>
        </Section>

        <Section title="10. International Transfers">
          <p>
            Our service providers may process your data in countries other
            than where you live, including the United States and the European
            Union. Where required, we rely on standard contractual clauses or
            other lawful transfer mechanisms.
          </p>
        </Section>

        <Section title="11. Children">
          <p>
            The Service is not intended for users under 18. We do not
            knowingly collect personal data from children. If you believe a
            minor has provided us with personal data, contact us and we will
            delete it.
          </p>
        </Section>

        <Section title="12. Cookies and Local Storage">
          <p>
            We use a small number of cookies and browser storage entries that
            are strictly necessary to operate the Service: an authentication
            session token, a language preference, a theme preference, and a
            UI-state cache. We do not use third-party advertising cookies.
          </p>
        </Section>

        <Section title="13. Changes to This Policy">
          <p>
            We may update this Privacy Policy. If changes are material, we
            will notify you by email or through the Service before they take
            effect. Continued use of the Service after the effective date
            indicates acceptance.
          </p>
        </Section>

        <Section title="14. Contact">
          <p>
            For privacy questions or requests, contact{' '}
            <a
              href="mailto:epimetheus.support@gmail.com?subject=Privacy%20question%20%E2%80%94%20Epimetheus&body=Hi%20Epimetheus%20team%2C%0A%0A"
              className="text-accent-primary hover:underline"
            >
              epimetheus.support@gmail.com
            </a>
            {' '}(or{' '}
            <a
              href="https://mail.google.com/mail/?view=cm&fs=1&to=epimetheus.support@gmail.com&su=Privacy%20question%20%E2%80%94%20Epimetheus&body=Hi%20Epimetheus%20team%2C%0A%0A"
              target="_blank"
              rel="noopener noreferrer"
              className="text-accent-primary hover:underline"
            >
              open in Gmail
            </a>
            ).
          </p>
        </Section>

        <p className="text-xs text-slate-600 pt-8 border-t border-white/5">
          This document is provided as a starting template and does not
          constitute legal advice. Please consult a qualified attorney in your
          jurisdiction (e.g., GDPR for the EEA / UK, CCPA for California, the
          Data Privacy Act of 2012 for the Philippines) before relying on it.
        </p>

        <div className="pt-4">
          <Link
            to="/terms"
            className="text-sm text-accent-primary hover:underline"
          >
            Read the Terms of Service →
          </Link>
        </div>
      </main>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="text-xl font-semibold text-slate-100">{title}</h2>
      <div className="text-sm text-slate-400 leading-relaxed space-y-3">
        {children}
      </div>
    </section>
  );
}
